// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEnDnJEcOqYZAc10YVkcno4wUzDf_adKA',
    appId: '1:320729121145:web:5adbe65fbef800421b6fa8',
    messagingSenderId: '320729121145',
    projectId: 't3-yalapay',
    authDomain: 't3-yalapay.firebaseapp.com',
    storageBucket: 't3-yalapay.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG5zeuTuPM6apM3oMRf7VlmnvziKdyXGY',
    appId: '1:320729121145:android:be7adf3d611d61321b6fa8',
    messagingSenderId: '320729121145',
    projectId: 't3-yalapay',
    storageBucket: 't3-yalapay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23TLuIzYyXBj2ZXL08F8Kp92_DnAY0Es',
    appId: '1:320729121145:ios:f827bf17078380791b6fa8',
    messagingSenderId: '320729121145',
    projectId: 't3-yalapay',
    storageBucket: 't3-yalapay.firebasestorage.app',
    iosBundleId: 'com.nitrogen.yalapay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB23TLuIzYyXBj2ZXL08F8Kp92_DnAY0Es',
    appId: '1:320729121145:ios:df82b679b42e308e1b6fa8',
    messagingSenderId: '320729121145',
    projectId: 't3-yalapay',
    storageBucket: 't3-yalapay.firebasestorage.app',
    iosBundleId: 'com.example.yalapay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEnDnJEcOqYZAc10YVkcno4wUzDf_adKA',
    appId: '1:320729121145:web:00816c337d15dee81b6fa8',
    messagingSenderId: '320729121145',
    projectId: 't3-yalapay',
    authDomain: 't3-yalapay.firebaseapp.com',
    storageBucket: 't3-yalapay.firebasestorage.app',
  );

}